---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Florian.
--- DateTime: 22/04/2022 14:57
---

fx_version 'adamant'
game 'gta5'

client_scripts {
    'src/RageUI.lua',
    'src/Menu.lua',
    'src/MenuController.lua',
    'src/components/*.lua',
    'src/elements/*.lua',
    'src/items/*.lua',
    'exemple.lua'
}
